# Generated by Django 5.2.17 on 2026-09-22 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TASK', 'Task'), ('APPOINTMENT', 'Appointment')], default='TASK', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_has_time', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at', 'due_at', 'created_at'],
                'indexes': [models.Index(fields=['status'], name='assistant_a_status_6b5593_idx'), models.Index(fields=['starts_at'], name='assistant_a_starts__1b13ad_idx'), models.Index(fields=['due_at'], name='assistant_a_due_at_02da93_idx')],
            },
        ),
    ]
