# Generated by Django 5.2.17 on 2026-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRequest',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('VOICE', 'Voice command'), ('AGENDA_SUMMARY', "Today's agenda summary")], default='VOICE', max_length=20)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('stage', models.CharField(choices=[('RECEIVED', 'Received'), ('TRANSCRIBED', 'Transcribed'), ('EXECUTING', 'Executing'), ('EXECUTED', 'Executed')], default='RECEIVED', max_length=20)),
                ('outcome', models.CharField(blank=True, default='', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('transcript', models.TextField(blank=True, default='')),
                ('reply_text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=5)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('audio', models.BinaryField(blank=True, null=True)),
                ('audio_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='assistant_v_created_d72405_idx'), models.Index(fields=['audio_expires_at'], name='assistant_v_audio_e_32c5ed_idx')],
            },
        ),
    ]
